name = "SymbolicDiagonalization"
uuid = "20400ecc-8495-4878-83aa-560642c30d15"
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
LinearAlgebra = "1.12.0"
Revise = "3.12.3"
Symbolics = "7.2.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
