[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
SymbolicDiagonalization = "20400ecc-8495-4878-83aa-560642c30d15"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[sources]
SymbolicDiagonalization = {path = "/home/vsilv/.nextcloud/src/SymbolicDiagonalization.jl"}
